  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
             <h1 class="header center teal-text text-lighten-2">Informazioni sul Tuo Immobile</h1>   
         <div class="row" style="width:70vh; margin-top: 5%;"
    <form class="col s12">
    
       <div class="row">
        <div class="input-field col s12">
          <input id="password" type="text" class="validate">
          <label for="password">Area Disponibile?</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="text" type="text" class="validate">
          <label for="password">Consumo Energetico Annuo?</label>
        </div>
        
      </div>
      <center>
         <p>
      <input name="group1" type="radio" id="test1" />
      <label for="test1">Tetto a Falda</label>
    </p>
    <p>
      <input name="group1" type="radio" id="test2" />
      <label for="test2">Tetto Piano</label>
    </p>
</center>
<div class="row center">
          <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Inserisci Dati</a>
        </div>
    </form>
        </div>