  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
  

  
                 <style>
                   .card
                   {
                      display:inline-block;
                      margin-left : 16.5%;
                      width:15%; height:25%
                   }                  
                 </style>
                              
                          
                  <div class="card"  >
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="<?=$this->baseUrl('images/prodotti/led.jpg');?>" >
    </div>
    <div class="card-content">
      <span title="Clicca per Informazioni complete" class="card-title activator grey-text text-darken-4">Card Title<i  class="material-icons right">more_vert</i></span>
      <p><a href="#">Aggiungi al Carrello</a></p>
    </div>
    <div class="card-reveal">
      <span title="Clicca per tornare alla foto" class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
 