  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
  

  
                 <style>
                   .card
                   {
                      display:inline-block;
                      margin-left : 16.5%;
                      width:15%; height:25%
                   }                  
                 </style>
                              
                          
                  <div class="card"  >
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="<?=$this->baseUrl('images/prodotti/led.jpg');?>" >
    </div>
    <div class="card-content">
      <span title="Clicca per Informazioni complete" class="card-title activator grey-text text-darken-4">Lampadina LED 4 W<i  class="material-icons right">more_vert</i></span>
      <p><a href="#">Aggiungi al Carrello</a></p>
    </div>
    <div class="card-reveal">
      <span title="Clicca per tornare alla foto" class="card-title grey-text text-darken-4">Venditore: GOOBAY<i class="material-icons right">close</i></span>
      <p>Descrizione del prodotto

• Lampadina LED SMD con attacco E27
• Luce bianca calda con 3000K, come una lampadina a incandescenza
• Risparmio energetico dell' 83% di energia rispetto a lampada standard
• Colori naturali grazie a 82 Ra
• Non si riscalda e si illumina in 0,05 secondi
• Di durata molto lunga, fino a 15 anni
• Dimmerabile 100% -10%

Vantaggi
• Bassa generazione di calore
• Alta efficienza energetica
• Basso consumo di corrente
• Elevata autonomia
• Bassi costi di manutenzione
• Mercurio-free
• Semplicità di sostituzione lampadina da incandescenza a LED

Durata
• Cicli accensione On/Off > 500.000
• Elevata capacità di commutazione di ~ 30.000 ore
• Durata del LED di 60.000 h ~

Caratteristiche
• Dimmerabile: 100-10% (si può regolare la luminosità)
• Classe energetica A
• Colore: bianco caldo
• Temperatura di colore 3000 K
• Intensità luminosa: 470 lumen
• Tensione 220-240 V AC
• Attacco E27
• Potenza led: 7.2 W
• Sostituzione incandescenza di 40 W
• Angolo di visuale 120°
• Assemblaggio: LED SMD
• Lunghezza 115 millimetri
• Diametro 60 mm
• Modello A60</p>
    </div>
  </div>
 