  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
      <div  style="width: 70%; margin-left: 15.5%;">
 <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">label_outline</i>Ordine del 15/10/2016</div>
      <div class="collapsible-body"><p>•10X Lampadine Led 4 W</p></div>
      <div class="collapsible-body"><p>Totale=75.90€    </p></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">label_outline</i>Ordine del 02/12/2014</div>
      <div class="collapsible-body"><p>•1X Mini Pala Eolica <br> •3X Lampadine Led</p></div>
      <div class="collapsible-body"><p>Totale=3200€</p></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">label_outline</i>Ordine del 14/03/2015</div>
      <div class="collapsible-body"><p>•4X Pannello Ariston <br> •3X Lampadine Led</p></div>
      <div class="collapsible-body"><p>Totale=5190€</p></div>
    </li>
  </ul>
    </div>