  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
  

  
                 <style>
                   .card
                   {
                      display:inline-block;
                      margin-left : 16.5%;
                      width:25%; height:25%
                   }                  
                 </style>
                              
                          
                  <div class="card"  >
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="<?=$this->baseUrl('images/prodotti/pale.jpg');?>" >
    </div>
    <div class="card-content">
      <span title="Clicca per Informazioni complete" class="card-title activator grey-text text-darken-4">Mini Generatore Eolico 1kW<i  class="material-icons right">more_vert</i></span>
      <p><a href="#">Aggiungi al Carrello</a></p>
    </div>
    <div class="card-reveal">
      <span title="Clicca per tornare alla foto" class="card-title grey-text text-darken-4">Venditore:PRAMAC<i class="material-icons right">close</i></span>
      <p> Le micro Turbine eoliche PRAMAC da 1 kW sono utilizzabili in molte applicazioni:

dalle abitazioni ai resorts turistici, dalle illuminazioni stradali alle strutture agricole e ovunque esse effettivamente abbassino i costi energetici e riducano l'impatto ambientale, combinando efficienza e design.

Questo è un modo intelligente per convertire l'energia in elettricità e soddisfare ogni giorno i bisogni energetici attraverso uno strumento estremamente efficiente e, allo stesso tempo, esteticamente attraente e silenzioso.</p>
    </div>
  </div>
 
                  