  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
  

  
                 <style>
                   .card
                   {
                      display:inline-block;
                      margin-left : 16.5%;
                      width:25%; height:25%
                   }                  
                 </style>
                              
                          
                  <div class="card"  >
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="<?=$this->baseUrl('images/prodotti/pannello300w.jpg');?>" >
    </div>
    <div class="card-content">
      <span title="Clicca per Informazioni complete" class="card-title activator grey-text text-darken-4">Pannello solare da 300W<i  class="material-icons right">more_vert</i></span>
      <p><a href="#">Aggiungi al Carrello</a></p>
    </div>
    <div class="card-reveal">
      <span title="Clicca per tornare alla foto" class="card-title grey-text text-darken-4">Venditore:ALEO<i class="material-icons right">close</i></span>
      <p>Pannello solare da 300W, dimensioni medie.</p>
    </div>
  </div>
 
                         <div class="card" >
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="<?=$this->baseUrl('images/prodotti/pannello_ariston.jpg');?>" >
    </div>
    <div class="card-content">
      <span title="Clicca per Informazioni complete" class="card-title activator grey-text text-darken-4">Pannello Kairos Ariston<i  class="material-icons right">more_vert</i></span>
      <p><a href="#">Aggiungi al Carrello</a></p>
    </div>
    <div class="card-reveal">
      <span title="Clicca per tornare alla foto" class="card-title grey-text text-darken-4">Venditore:ARISTON<i class="material-icons right">close</i></span>
      <p>Collettore solare ad alto rendimento adatto ad impianti solari a circolazione forzata di grandi dimensioni.
Lo scambiatore a serpentina, l’esclusivo assorbitore con trattamento superficiale blu altamente selettivo e il vetro solare temperato ad alta trasparenza, garantiscono la massima captazione di energia solare.
Grazie alle elevate tecnologie utilizzate l’installazione di Kairos XP 2.5-1 V, con struttura scatolata in alluminio anodizzato, connessioni a innesto rapido e pozzetto porta sonda integrato, risulta estremamente semplificata.</p>
    </div>
  </div>
            
                 
           