  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
  <br><br>
  
  <h5 class="header col s12 light">Inserisci il comune di residenza.</h5>
  <div class="row">
        <div class="input-field col s12">
          <input id="text" type="text" class="validate">
          <label for="Inserisci">Inserisci Comune</label>
        </div>
      </div>
  <div align="center">
      <div class="row center">
          <a href="#" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Conferma</a>
        </div>

<iframe
id="iframemap"
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/search?key=AIzaSyCTjbj_bigtP6Tffc-fFm2HK62QEWmye9Q&q=riparazioni+caldaie+italia" allowfullscreen>
</iframe>

</div>
  