  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
  

  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-lighten-2">Energia Idroelettrica, la piu' utilizzata.</h1>
        <div class="row center">
          <h5 class="header col s12 light"> Scopriamone il motivo.</h5>  
        </div>
        <div class="row center">
          <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Confronta i dati aggiornati al 2016</a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="../images/background1.jpg" alt="Unsplashed background img 1"></div>
  </div>



         
      

  

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text" class="icon-block"></i></h3>
          <h4>Il Motivo</h4>
          <p class="left-align light">    L'energia idroelettrica e' la principale risorsa alternativa alle fonti fossili usata in Italia e garantisce circa il 15% del fabbisogno energetico italiano. La sua importanza in passato fu molto piu' grande perche' dagli inizi del XX secolo sino al primo dopoguerra l'energia idroelettrica rappresentava la grande maggioranza dell'energia prodotta in Italia arrivando anche a toccare punte di poco inferiori al 100%. </p>
            <p>Per maggiori informazioni in dettaglio si puo' visitare <a href="https://it.wikipedia.org/wiki/Produzione_di_energia_elettrica_in_Italia">Questa Pagina.</a>  </p>
            </div>
      </div>

    </div>
  </div>

          <div class="slider">
    <ul class="slides">
      <li>
        <img src="../images/3.jpg"> <!-- random image -->
        <div class="caption center-align">
          <h3>Alcuni dei nostri Lavori.</h3>
          <h5 class="light grey-text text-lighten-3"></h5>
        </div>
      </li>
      <li>
        <img src="../images/2.jpg"> <!-- random image -->
        <div class="caption left-align">
          <h3>Alcuni dei nostri Lavori.</h3>
        </div>
      </li>
      <li>
        <img src="../images/1.jpg"> <!-- random image -->
        <div class="caption right-align">
          <h3>Alcuni dei nostri Lavori.</h3>
        </div>
      </li>
      <li>
        <img src="../images/4.jpg"> <!-- random image -->
        <div class="caption center-align">
          <h3>Alcuni dei nostri Lavori.</h3>
          
        </div>
      </li>
    </ul>
  </div>
      
  


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="../js/materialize.js"></script>
  <script src="../js/init.js"></script>

  <script>
   $(document).ready(function() {

    $('.collapsible').collapsible();
    $('.slider').slider({
        full_width: true
    });
    $('.materialboxed').materialbox();
});
  </script>