  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
    <div class="slider">
    <ul class="slides">
      <li>
        <img src="<?=$this->baseUrl('images/slide1.jpg');?>"> <!-- random image -->
        <div class="caption center-align">
          <h3>Benvenuto su Greenergy</h3>
          <h5 class="light grey-text text-lighten-3">Il portale della salvaguardia ambientale e personale</h5>
        </div>
      </li>
      <li>
        <img src="<?=$this->baseUrl('images/slide2.jpg');?>"> <!-- random image -->
        <div class="caption left-align">
          <h3>Dal'idroelettrico</h3>
          <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
        </div>
      </li>
      <li>
        <img src="<?=$this->baseUrl('images/slide3.jpg');?>"> <!-- random image -->
        <div class="caption right-align">
          <h3>Ai pannelli solari ed al campo eolico</h3>
          <h5 class="light grey-text text-lighten-3">Un settore sempre più in ampliamento.</h5>
        </div>
      </li>
      <li>
        <img src="<?=$this->baseUrl('images/slide4.jpg');?>"> <!-- random image -->
        <div class="caption center-align">
          <h3>Cosa aspetti?</h3>
          <h5 class="light grey-text text-lighten-3">Aiutaci a Salvare il Pianeta!</h5>
          <div class="row center">
          <a href="<?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'signup'),
                        'default',true
                    ); 
                 ?>" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Registrati</a>
        </div>
        </div>
      </li>
    </ul>
  </div>
  

  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Risparmio Energetico</h5>

            <p class="light">Grazie al nostro EECT(Energy Efficiency Calculation Tool) puoi calcolare le spese* di casa tua e revisionare i tuoi consumi.</p>
            <p class="light" style="font-size: 11px">(*Il calcolo è solo una stima, non rappresenta il consumo effettivo)</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Scelta del Prodotto più adatto a te</h5>

            <p class="light">Dopo aver valutato l'efficienza energetica di casa tua potrai visualizzare i tuoi consumi e ti proporremo un prodotto che soddisfi le tue esigenze.</p>
          </div>
        </div>
        
        
        
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">language</i></h2>
            <h5 class="center">Manutenzione e Realizzazione Impianti eolici e Centrali Idroelettriche</h5>

            <p class="light"></p>
          </div>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light"></h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="<?=$this->baseUrl('images/1.jpg');?>" alt="Unsplashed background img 2"></div>
  </div>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Contact Us</h4>
          <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="images/pale.jpg" alt="Unsplashed background img 3"></div>
  </div>
