  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
  <div>
  <div class="row" style="width:70vh; margin-top: 5%;"
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <input placeholder="Placeholder" id="first_name" type="text" class="validate">
          <label for="first_name">First Name</label>
        </div>
        <div class="input-field col s6">
          <input id="last_name" type="text" class="validate">
          <label for="last_name">Last Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>
      <div class="file-field input-field">
      <div class="btn">
        <span>File</span>
        <input type="file" multiple>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="Carica la tua foto profilo">
      </div>
    </div>
      <div class="row center">
          <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Registrati</a>
        </div>
    </form>
  </div>
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <div class="row center">
        </div>
        
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="<?=$this->baseUrl('images/eolica.jpg'); ?>" alt="Unsplashed background img 1" style="display: block; transform: translate3d(-50%, 1059px, 0px);"></div>
  </div>
</div>