  <?php $this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.1.min.js')
    ->appendFile($this->baseUrl('js/materialize.js'))
    ->appendFile($this->baseUrl('js/init.js'));
  ?>
  <div>
  <div class="row" style="width:70vh; margin-top: 5%;"
    <form class="col s12">
    
       <div class="row">
        <div class="input-field col s12">
          <input id="password" type="text" class="validate">
          <label for="password">CODICE UNIVOCO VENDITORE</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>
      
        
      <div class="row center">
          <a href="<?= $this->url(array(
                        'controller' => 'vendor',
                        'action'     => 'index'),
                        'default',true
                    ); 
                 ?>" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Accesso Venditore</a>
        </div>
    </form>
  </div>
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <div class="row center">
        </div>
        
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="<?=$this->baseUrl('images/eolica.jpg'); ?>" alt="Unsplashed background img 1" style="display: block; transform: translate3d(-50%, 1059px, 0px);"></div>
  </div>
</div>