<footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Chi Siamo.</h5>
          <p class="grey-text text-lighten-4">Greenergy, Leader nel settore del risparmio. <br>Made In Fabriano</p>


        </div>
        
        <div class="col l3 s12">
          <h5 class="white-text">Seguici sui Social!</h5>
          <ul>
           <a href="http://www.facebook.com"> <img src="<?=$this->baseUrl('images/facebook.png');?>"></a>
            <a href="http://www.twitter.com"> <img src="<?=$this->baseUrl('images/twitter.png');?>"></a>
           <a href="http://www.linkedin.com">  <img src="<?=$this->baseUrl('images/linkedin.png');?>"></a>
           <a href="http://plus.google.com">  <img src="<?=$this->baseUrl('images/google.png');?>"></a>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">CebaRox</a>
      </div>
    </div>
  </footer>