<nav class="white" role="navigation">
    <div class="nav-wrapper container">
      
           <a id="logo-container" href="#" class="brand-logo">  <img src="images/leafgreen.png" />Greenergy</a>
        <ul class="right hide-on-med-and-down">
            <li><a href="<?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login'),
                        'default',true
                    ); 
                 ?>">Login</a></li>
        </ul>
         <ul id="nav-mobile" class="side-nav">
        <li><a href="<?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login'),
                        'default',true
                    ); 
                 ?>">Login</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
</nav>