<ul>
	<li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default', true
                    ); 
                 ?>"
		title="Torna al Catalogo">Catalogo</a></li>

	<li><a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'index',
                        ), 
                        'default', true
                    ); 
                 ?>"
		title="Azione1">Azione1</a></li>
	<li><a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'index',
                        ), 
                        'default', true
                    ); 
                 ?>"
		title="Azione2">Azione2</a></li>
	<li><a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'index',
                        ), 
                        'default', true
                    ); 
                 ?>"
		title="Azione3">Azione3</a></li>
	<li><a
		href="
                <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'logout',
                         ), 
                        'default', true
                    ); 
                 ?>"
		title="Esci dall'Area Amministratore">Logout</a></li>
</ul>
