
        <ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">Italiano</a></li>
  <li><a href="#!">Inglese</a></li>
  <li><a href="#!">Francese</a></li>
    <li><a href="#!">Tedesco</a></li>
      <li><a href="#!">Albanese</a></li><br>  <li><a href="#!">Cinese</a></li><br>
</ul>                         
   <nav class="white" role="navigation">                
    <div class="nav-wrapper container">                      
      <a id="logo-container" href="<?= $this->url(array(
                        'controller' => 'vendor',
                        'action'     => 'index'),
                        'default',true
                    ); 
                 ?>" class="brand-logo">  <img src="<?=$this->baseUrl('images/leafgreennew.png');?>" />Greenergy</a>     
      <ul  data-activates="slide-out" class="button-collapse" class="right hide-on-med-and-down" style="float:right">
        <li><a href="#">Account</a></li>
        <li><a id ="btn"class="dropdown-button" href="#!" data-activates="dropdown1">Lingua<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
                                                                                                 
      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Account</a></li>

      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>                                                    
  </nav>
  
  
  
  
                 <ul id="slide-out" class="side-nav" >
    <li><div class="userView">
      <img class="background" src="<?=$this->baseUrl('images/office.jpg');?>">
      <a href="#!user"><img class="circle" src="<?=$this->baseUrl('images/jim.jpg');?>"></a>
      <a href="#!name"><span class="white-text name">Jenny Doe</span></a>
      <a href="#!email"><span class="white-text email">jDoe@gmail.com</span></a>
    </div></li>        
    
        
        
    <li><a href="<?= $this->url(array(
                        'controller' => 'vendor',
                        'action'     => 'accountsettings'),
                        'default',true
                    ); 
                 ?>"><i class="material-icons">perm_identity</i>Impostazioni Account</a></li>
    
      
                 
                 
                 
           
            <li><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'rimuoviprodotto'),
                        'default',true
                    ); 
                 ?>"><i class="material-icons">replay</i>Rimuovi Prodotto</a></li>     
      
        
        
        
       
 
        
        
    <li><div class="divider"></div></li>
    <li><a class="waves-effect" href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'logout'),
                        'default',true
                    ); 
                 ?>">Disconnettiti</a></li>
  </ul>

   



<script>
$("#btn").click(function(ev) {
ev.stopPropagation();
});

$('#dropdown1').click(function() {  location.reload(); return false;  });   
</script>