<?php echo $this->doctype() ?>
<html>
<head>
	<!--<?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?> -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="<?=$this->baseUrl('css/materialize.css'); ?>" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="<?=$this->baseUrl('css/style.css'); ?>" type="text/css" rel="stylesheet" media="screen,projection"/>
    <?= $this->headScript(); ?>
</head>
<body>
        <?= $this->render('_topnavmain.phtml') ?>

	<!-- end #menu -->
	
	  	  <?php echo $this->layout()->content; ?>

	<!-- end #content -->
	   <?= $this->render('_footer.phtml') ?>

	<!-- end #footer -->
</div>
</body>
</html>