<?php echo $this->doctype() ?>
<html>
<head>
	 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="<?=$this->baseUrl('css/materialize.css'); ?>" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="<?=$this->baseUrl('css/style.css'); ?>" type="text/css" rel="stylesheet" media="screen,projection"/>
    <?= $this->headScript(); ?>
</head>
<body id="bodyadmin">
<div id="wrapper">
	<div id="menu">
        <?= $this->render('_topnavvendor.phtml') ?>
	</div>

	<!-- end #menu -->
	<div id="page">
  	  <div id="page-bgtop">
    	<div id="page-bgbtm">
	  	  <?php echo $this->layout()->content; ?>
      	<div style="clear: both;">&nbsp;</div>
	    </div>
  	  </div>
	</div>

	<!-- end #content -->
	<?= $this->render('_footer.phtml') ?>
	<!-- end #footer -->
</div>
</body>
</html>